### ISSUE TITLE
Restrict Cluster Radius

### ISSUE THREAD

**Issue by cmkalman** [tkhrotn/rflexscan#2]
I'm looking to restrict the maximum spatial cluster size in my analysis similar to what can be done in the SaTScan application. Is it possible to do this with the existing package?

**Comment by tkhrotn** [comment]
The existing package allows you to specify the maximum number of regions in a cluster by _clustersize_ argument, but not the maximum radius. I am currently implementing this option and will be able to provide it soon.

**Comment by tkhrotn** [comment]
The _clusterradius_ argument, which specifies the maximum radius of a cluster, is implemented. Note that the cluster size is also limited by _clustersize_ argument; by inputting the total number of regions into _clustersize_ argument, the cluster size can be limited only by the maximum radius. The new version has not yet been submitted to CRAN and should be installed from github using devtools.

**Comment by cmkalman** [comment]
Thank you! I very much appreciate your speedy response in implementing this. 
I have tried out the new argument; however the result does not appear to be as expected from implementing the same argument in SaTScan. It seems to be the same result as before. 

I did not specify a cluster size and instead only used the cluterradius argument to restrict the radius to 5km (clusterradius=5).

Can you explain further what you mean when you say that the cluster size can be limited only by the maximum radius?

**Comment by tkhrotn** [comment]
If the clustersize argument is not specified, the default of 15 is used. This means that the maximum number of regions in a cluster to be detected is 15. To remove this limitation, for example, use clustersize=100 if the total number of regions in the data is 100. In addition to this specification, use clusterradius=5 to limit the radius to 5 km.
